### ISSUE TITLE
USER STORY: GOOGLE ANALYTICS

### ISSUE THREAD

**Issue by Seiyaroo** [PelletierConstructionGroup/PelletierConstructionGroup.github.io#1]
As a Developer, I want to implement Google Analytics for the website so that our client can track necessary information such as length of time spent on the site, where users are visiting from, and more.

I will provide various resources to get started, and provide visuals so that our client can best give us information as to what they would like.

**Comment by Seiyaroo** [comment]
https://www.paperstreet.com/blog/how-to-setup-and-install-google-analytics-on-your-website/  https://support.google.com/analytics/answer/9304153?hl=en  
https://youtu.be/XPuWgkd3RCs

Some resources I've found and can be utilized to get something up and running. I might give this a test on my personal site if capable later on this week.

**Comment by Diego-Cano** [comment]
After doing some research, I have found some useful links and tips on how to efficiently take advantage of Google Analytics. Specifically, it can be helpful to utilize the newest features of Google Analytics 4.0, which is the most current version. As a team, we could set up personalized notifications for our client regarding its website traffic, so we can offer a better-tailored experience for its users.

Links: 
https://databox.com/advanced-google-analytics-hacks
https://www.semrush.com/blog/advanced-goog
https://neilpatel.com/blog/google-analytics-tips/

Other advanced features that we could implement for this project (if possible and approved):
-Data-Driven Attribution (DDA).
-Setting Up Goals with Events.
-Anomaly Detection.
-Custom Alerts (as mentioned above).

<img width="471" alt="Screenshot 2024-04-18 at 12 27 48 PM" src="https://github.com/PelletierConstructionGroup/PelletierConstructionGroup.github.io/assets/64940291/edeeb063-e621-4b9c-9603-2114c5207735">

**Comment by Diego-Cano** [comment]
Hey team, I’ve been digging into Google Analytics 4.0 lately. There’s a lot of cool stuff in there like Data-Driven Attribution and Custom Alerts that could really amp up our project.

I found some solid breakdowns and guides on how to use these features. Definitely check out the Google Analytics Academy—they’ve got everything from beginner to advanced stuff. Also, hitting up some analytics blogs can give us more practical insights; they usually have step-by-step posts that make the complex stuff easier to grasp.

Let’s chat more about this in our next meeting and see how we can roll these features into our work. Can’t wait to hear what you all think!

Here are some useful links: 

https://support.google.com/analytics/answer/10089681?hl=en

https://www.dunhamandcompany.com/data/google-analytics-4-is-it-for-me/?gad_source=1&gclid=CjwKCAjw26KxBhBDEiwAu6KXt752LZA8epruId_jb4SIYnctFPDq6QAjrDoGiAbsBE0_14jX9g-kXRoCWq8QAvD_BwE

https://analytics.google.com/analytics/academy/
