### ISSUE TITLE
USER STORY: Remove houzz assets and css styles.

### ISSUE THREAD

**Issue by TuongPhamM** [PelletierConstructionGroup/PelletierConstructionGroup.github.io#2]
As a developer, I want to remove assets/styles generated by houzz to fully allow us to customize the website on client's need.

Information:
- [Sprint note](https://miro.com/app/board/uXjVKWBRUGs=/?moveToWidget=3458764585420588363&cot=10)
- [About houzz website builder.](https://www.houzz.com/for-pros/feature-business-website)
- [PCG Website](https://pelletierconstructiongroup.com/)
-  [Taskboard](https://nscad.slack.com/docs/T11JCT3RN/F06UVNWAAMQ)

Everyone feel free to correct the USER STORY. 

- [x] #4 -Tuong
- [ ] #5 - Lars
- [ ] #8 - Omar
- [ ] #10 - Xinran
- [ ] #12 - Elida

**Comment by larsswenson** [comment]
I've been working on removing houzz logos/links from the pages index.html, about, contacts, projects, testimonials, etc. So far I've been able to remove the houzz social media link from index.html but still working on others! It doesn't surprise me that houzz wouldn't make it easy to remove their proprietary branding!

**Comment by TuongPhamM** [comment]
> I've been working on removing houzz logos/links from the pages index.html, about, contacts, projects, testimonials, etc. So far I've been able to remove the houzz social media link from index.html but still working on others! It doesn't surprise me that houzz wouldn't make it easy to remove their proprietary branding!

Nice! I think we should avoid working on the same file which causes merge conflicts, I guess the rest of us will work on HTML files in the projects/ folder and leave the outer files for you, what do you think? @larsswenson

**Comment by ogarmela** [comment]
How can we avoid task conflicts and overlapping

**Comment by larsswenson** [comment]
@TuongPhamM OK, I finished removing all of the houzz logos/links I could find from the outer files (index.html, about, contact, etc.). I'll initiate a pull request shortly.

**Comment by el-riber** [comment]
I am working  on 7167797-wrap-around-deck-with-patio-cover.html. And 7167814-modern-porch.html

**Comment by taylorpapke** [comment]
> I am working on 7167797-wrap-around-deck-with-patio-cover.html. And 7167814-modern-porch.html files

I think this is a good idea for people to split up the remaining work. It appears that @larsswenson has already completed all of the outer pages which means that all that is left are the individual project pages that are linked from the home and projects page. It appears that the only difference with the home page is that it includes 3 extra projects: railing, modern porch and new shop. This makes for a total of 12 project pages.

@el-riber is doing the wrap around deck with patio cover and the modern porch.

This leaves the following pages for @ogarmela, @TuongPhamM or anyone else:
- railing
- new shop
- open concept kitchen
- mukilteo house
- ranch home update
- timber frame barn
- composite deck
- Great Wall of lake city
- bathroom expansion
- bathroom

Please claim what you are doing in this thread and make an issue for it right away. In the issue, also list what pages you are doing so there is no confusion/duplicate work.

**Comment by TuongPhamM** [comment]
> > I am working on 7167797-wrap-around-deck-with-patio-cover.html. And 7167814-modern-porch.html files
> 
> I think this is a good idea for people to split up the remaining work. It appears that @larsswenson has already completed all of the outer pages which means that all that is left are the individual project pages that are linked from the home and projects page. It appears that the only difference with the home page is that it includes 3 extra projects: railing, modern porch and new shop. This makes for a total of 12 project pages.
> 
> @el-riber is doing the wrap around deck with patio cover and the modern porch.
> 
> This leaves the following pages for @ogarmela, @TuongPhamM or anyone else:
> 
> * railing
> * new shop
> * open concept kitchen
> * mukilteo house
> * ranch home update
> * timber frame barn
> * composite deck
> * Great Wall of lake city
> * bathroom expansion
> * bathroom
> 
> Please claim what you are doing in this thread and make an issue for it right away. In the issue, also list what pages you are doing so there is no confusion/duplicate work.

Yes, we have a channel and are using Slack canvas to keep track on this. https://nscad.slack.com/docs/T11JCT3RN/F06UVNWAAMQ

**Comment by JoyZhang2023** [comment]
@TuongPhamM Joining force! I will be working on Great Wall of Lake City and Composite Deck. New issue created #10 .

**Comment by TuongPhamM** [comment]
> @TuongPhamM Joining force! I will be working on Great Wall of Lake City and Composite Deck. New issue created #10 .

great to hear, we have a little Slack sub-channel for who's working on this User Story where we discuss and have resource. What's your name on Slack?

**Comment by intisarosman1** [comment]
I would like to join and work on any tasks no one else is working on!

**Comment by TuongPhamM** [comment]
> I would like to join and work on any tasks no one else is working on!

I have added you to our Slack channel.
