### ISSUE TITLE
USER STORY: Contact Page Form

### ISSUE THREAD

**Issue by heosman** [PelletierConstructionGroup/PelletierConstructionGroup.github.io#42]
As a developer, I will want to replace the current contact form with a Google form.

Tasks:
- [x] [Create Google form based on current contact form. ](https://forms.gle/N7myENfPkhxGYhyn8)
- [x] Replace current contact form with embedded Google form.

**Comment by taylorpapke** [comment]
@Seiyaroo Looks like @heosman is taking up this task. Is there any additional information that we can give her in regard to this or is this straightforward enough?

**Comment by Seiyaroo** [comment]
@taylorpapke @heosman I haven't found anything this morning that i've been researching it really should for now just be copy paste into place. Adjust width + height to fit page. We might have some styling to do in regards to making it better looking depending on what the embed does but once you have it in Hanan if you don't mind pinging us we can all take a peek :D
